codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 75%
        threshold: 0%
        flags:
          - unit
        paths:
          - "src"