name: Scheduled

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  testing:
    name: Testing
    strategy:
      matrix:
        os: ["windows-2019", "ubuntu-16.04", "ubuntu-18.04", "macOS-latest"]
        toolchain: ["stable", "beta", "nightly"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install the Rust toolchain
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          default: true

      - name: Attempt to restore the compiled artifacts from cache
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.os }}-${{ steps.toolchain.outputs.rustc_hash }}-build-${{ hashFiles('Cargo.lock') }}

      - name: Build
        id: build
        run: cargo build --all-targets --all-features --verbose

      - name: Perform unit testing and integration testing
        run: cargo test --workspace --all-targets --all-features

      - name: Perform documentation tests
        run: cargo test --doc